on:
  push:
    branches: ['main']

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.136.5'
          extended: true

      - name: Prepare content
        shell: bash
        run: |
          find content/ \
              -type f \
              -name "*.md" \
              -exec sed -i -E 's|(!\[[^]]*\]\()\/*([^)]*\))|\1/\2|g' {} +

          find content/ \
              -type f \( \
              -iname "*.jpeg" -o -iname "*.jpg" -o -iname "*.png" -o \
              -iname "*.gif" -o -iname "*.webp" -o \
              \) -exec mv {} static/ \;

      - name: Build
        run: hugo --minify

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          publish-dir: ./public
          production-branch: main
